### ISSUE TITLE
Where is the dataset processed? 

### ISSUE THREAD

**Issue by jg39gao** [epic-kitchens/action-models#16]
HI , Dear Prof

Thank you first for this excellent repo~
I am recently conducting TSN and TRN on Epic-Kitchen dataset. However, I didn't find the exact place where you process the kitchen dataset. Maybe I just too careless to find that out, Would you mind pointing that out?   
Thank you very very much~~

Faithfully 
Gao

**Comment by JJBOY** [comment]
Hello, have you found a efficient way to read and process the kitchen dataset?

**Comment by willprice** [comment]
Please see https://github.com/epic-kitchens/epic-kitchens-55-starter-kit-action-recognition for details on how to use our GulpIO adapter to ingest the dataset for use with gulpio.
