### ISSUE TITLE
Test Clips

### ISSUE THREAD

**Issue by saraalrawi** [epic-kitchens/action-models#17]
Hello, 

maybe the question is quite stupid, but I trying to get the following test clips: 

{"v_id": "P01_18", "start": 27355, "stop": 27463, "verb": 1, "noun": 18} 
{"v_id": "P22_15", "start": 12976, "stop": 13066, "verb": 0, "noun": 2}
{"v_id": "P01_18", "start": 113331, "stop": 113497, "verb": 1, "noun": 21}
{"v_id": "P02_09", "start": 36194, "stop": 36274, "verb": 3, "noun": 10}
{"v_id": "P06_09", "start": 264, "stop": 341, "verb": 2, "noun": 10}
{"v_id": "P01_18", "start": 175489, "stop": 175556, "verb": 9, "noun": 6}
{"v_id": "P03_20", "start": 655, "stop": 724, "verb": 0, "noun": 27}
{"v_id": "P22_16", "start": 78997, "stop": 79095, "verb": 2, "noun": 8}
{"v_id": "P30_11", "start": 6381, "stop": 6487, "verb": 1, "noun": 7}
{"v_id": "P01_19", "start": 9240, "stop": 9302, "verb": 0, "noun": 21}
{"v_id": "P22_16", "start": 36970, "stop": 37023, "verb": 12, "noun": 28}
{"v_id": "P24_07", "start": 16243, "stop": 16327, "verb": 2, "noun": 12}
{"v_id": "P06_09", "start": 78742, "stop": 78830, "verb": 0, "noun": 18}
-------------------------------------------------------------------------------------------------
I have downloaded the dataset, so I have: frames_rgb_flow  object_detection_images, with train and test splits. 
But I can find the video ids mentioned above, could you please help me? 
Thanks in advance!

**Comment by willprice** [comment]
See https://epic-kitchens.readthedocs.io/en/stable/cli_tools.html#action-segmentation for how to split the frames into action segments.
