### ISSUE TITLE
Exception while importing pretrainedmodels.

### ISSUE THREAD

**Issue by ahsaniqbal** [epic-kitchens/action-models#18]
Hey, 

I am trying to load pretrained models using pytorch hub. However, there is exception in tsn.py at line 35 (import pretrainedmodels). Can you please help me how I can fix this.

**Comment by willprice** [comment]
![image](https://user-images.githubusercontent.com/966205/87323283-7aecf480-c526-11ea-85af-ac08562c631d.png)
Note the instructions in the README to install Remi' Cadene's pretrainedmodels repo. Alternatively use the provided conda environment description (`environment.yml`)
