### ISSUE TITLE
attribute error module 'pretrainedmodels.models.torchvision_models' has no attribute 'ResNet'" after downloading the action models

### ISSUE THREAD

**Issue by alanyannick** [epic-kitchens/action-models#4]
Hi,

Thanks for this kind repo.
I just configured the environment followed with torch.hub but I met the issues described that "attribute error module 'pretrainedmodels.models.torchvision_models' has no attribute 'ResNet'" after downloading the action models. Is it related to the reference pretrainedmodels git?

Appreciate any helps.

**Comment by alanyannick** [comment]
I solved it by installing the github link of the pretrained-model you provided locally rather than "pip install "pretrainedmodels". "  Thanks anyway :)

**Comment by willprice** [comment]
Hi @alanyannick,
Glad you got it sorted. Yes, the version of `pretrainedmodels` we rely on is a fork of the original so the exception you got is an expected one. A quick way of creating an isolated environment with the required dependencies is through `conda-env`:

```bash
$ git clone https://github.com/epic-kitchens/action-models.git epic-action-models
$ cd epic-action-models
$ conda env create -n epic-models -f environment.yml
$ conda activate epic-models
```
